language: python
python:
  - "3.7.1"
# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install importlib-metadata==4.9.0
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
# command to run tests
script:
  - black --check .

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAWDMRPKVWBHWBU2H4"
  secret_access_key:
    secure: "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"
  region: "us-east-1"
  app: "mysite1"
  env: "django-env4"
  bucket_name: "elasticbeanstalk-us-east-1-419601274220"
  on:
    repo: api2062/swe-app
    branches:    
      only:
        - main
