language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - black --check .
  - flake8 

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAWDMRPKVWBHWBU2H4"
  secret_access_key:
    secure: "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"
  region: "us-east-1"
  app: "mysite1"
  env: "django-env4"
  bucket_name: "elasticbeanstalk-us-east-1-419601274220"
