language: python
python:
  - "3.7.1"
# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install importlib-metadata==4.9.0
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
# command to run tests
script:
  - black --check .

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "gzsoApavmYocCdoyevEVsvoxyzyOymTjvtJ+M0pQe4dMB9x66YZ4s9jG0B4g18e/KduCFbBW9HXtJLIQ6x4YPUhqdGRXttMQFzAb3O55JC6npountZvaJ/dBcCHLGkFbt1KZrwgI7nWt4ptZnd0kYHa9GZWkUQWuhR2yU1WYRTF0J7974HHwBOLolY+oakl/jaXDz2qlwFnw/H7vjrhxaqeEXrbazF4sgLo3MVEHCTTn9X/AIRyHplGCfRAHYpwwuiDSGubpqZ039z3De6ZbZTYvBOco8DZQS4kGTcdBkx/ZuWezfr8bF73gZg4Y6H9TkivqmUT1bAMNr2PtIQT99MHMkiVBRNkaQr/H2N1NAvXTfrnQxZfH/iVeh+MBS1qrS1s/VmA1Jg7fEkh/uSMKHchYXm4V4YYKlLKNSP4UlaIY/AGMR9hxP3ST9iBjsbYOdf1uoAJMw1SjDgRtrO9l7zuKXZTfQ9N/WpR7NyIwZ37CkvfG5LPUybW86CyxV0If/guDB+Z3XJk7ZIa+5+s7l6VBoL1toQEvsVsolonkTri4FlcNrqJACgiMQJVBM3N0w6hY2xCNDa+5RNIZ33iI6HVuqQxs/00Al82Lq7/get+KfPrk7LvgPXJ6OlZIheOAdp0H1G4HLpuk7bOZ78756Y8a/tTmrqv5fqUhKS8UrbA="
  secret_access_key:
    secure: "pDr5LYNl6vHMlrUh2c0/hiAnoxqSG7eqLj4ppLRll8pFiUBs7dZ5SZt5zbpY4jXxXmT6uCd8M81lAuU1JRlPuQfMqG1M/ayF9oDoxH4F9u88YST2GNuJWWnspG59Ja9HUCquWmF5XIpeDxiqfP28dzOwPAqD3cmbowiOngbkS/PXpnG54SI0E809TmDARgjFap8bQ2y5fPFJOwFE1pyuos/91y+tO1wTZ+IiRHsDtvvGL1XGveY+IHbqU2fOkLXv72VsYTh+f3iOyV7ms86i3sUu+qHgVJniEkfl8Fn8y9k/wFnYl0Q484gztsV2NRt+ABEQ/VnQoZKkthqrKkj+zOQdjQBgUvX2fWT/rxkihsvFAbIj3bfFpPaLue6GsTmPqA1+QFEtPEHxdPE/WlhvKup0XU/sZHqXxmEtupeweL0CQXT5n1VSBGaA5upAcuj3cfcU3qvZstF40zhLpaVbZCW7ebwgqtYhHSg3yxmYxlTUnRRWJYHjUJ+enTOmh46gT+SYTvt0X03Xch5VEdTMJO2J6uioMeLjsHf6S3/6BBDCg+3SO6PjShUY5yKENNF2ma9isQG40vzAryjbr8V4MWTqeIdrk0aE4S91t0gcf4hTiASacV+n39iVSfFLlAoMW7J4IkMJVgC08NvzSdMYAzY418A3A42kmU9Du7ZWgwY="
  region: "us-east-1"
  app: "mysite1"
  env: "django-env4"
  on:
    branches: master


    
